/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.act.a;
import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
  

    public class CAFETERIA extends javax.swing.JFrame {

        /**
         * Creates new form CAFETERIA
         */
        public CAFETERIA() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        btn4 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 30));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 30));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 30));

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, 30));
        getContentPane().add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, 30));

        btn1.setText("SHOW");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 90, 30));

        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 100, 30));
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, 30));
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 343, 100, 30));

        btn2.setText("CALCULATE");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 100, 30));
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 343, 100, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        btn3.setText("CALCULATE");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 100, 30));

        jLabel4.setText("[4] - COKE  35");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel5.setText("[5] - SPRITE  25");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel6.setText("[5] - ROYAL  20");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel7.setText("[3] - CHOCOLATE CAKE 45");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 96, -1, 20));

        jLabel8.setText("[2] - VANILLA CAKE 40");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel9.setText("[1] - CHEESE CAKE 30");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("DRINKS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 70, 20));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 270, 102, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("MENU");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("SNACKS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        try {
            int choice = Integer.parseInt(txt1.getText());
            double price = 0.0;
            String name = "";

            if (choice == 1) {
                name = "cheese cake";
                price = 30;
            } else if (choice == 2) {
                name = "vanilla cake";
                price = 40;
            } else if (choice == 3) {
                name = "cheese cake";
                price = 45;
            } else if (choice == 4) {
                name = "coke";
                price = 35;
            } else if (choice == 5) {
                name = "sprite";
                price = 25;
            } else if (choice == 6) {
                name = "royal";
                price = 35;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please Enter 1-6!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            txt2.setText(name);
            txt3.setText(name);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter 1-6!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        try {

            if (txt3.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "PLEASE CLICK SHOW BUTTON FIRST!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int quantity = Integer.parseInt(txt4.getText());
            double price = Double.parseDouble(txt3.getText());

            double total = price * quantity;
            txt5.setText("" + total);
            txt6.setText("" + total);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "PLEASE ENTER INVALID QUANTITY", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
            // TODO add your handling code here:
            try {
                if (txt6.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "PLEASE CLICK TOTAL BUTTON FIRST", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                double total = Double.parseDouble(txt6.getText());
                double cash = Double.parseDouble(txt7.getText());

                if (cash < total) {
                    JOptionPane.showMessageDialog(rootPane, "INSUFFICIENT CASH!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txt7.setText("");
                    txt7.requestFocus();
                    return;
                }

                double change = cash - total;
                txt8.setText("" + change);

                JOptionPane.showMessageDialog(rootPane, "THANK YOU FOR ORDERING!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "ENTER VALID CASH!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
      txt1.setText("");
      txt2.setText("");
      txt3.setText("");
      txt4.setText("");
      txt5.setText("");
      txt6.setText("");
      txt7.setText("");
      txt8.setText("");
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txt5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()  {
              new CAFETERIA().setVisible(true)        
            }
        });
                
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    // End of variables declaration//GEN-END:variables

