/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.act.a;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CAFETERIA_ORDER2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CAFETERIA_ORDER2.class.getName());

    /**
     * Creates new form CAFETERIA_ORDER2
     */
    public CAFETERIA_ORDER2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("[1] - CHEESE CAKE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("[2] - VANILLA CAKE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("[3] - CHOCOLATE CAKE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("SNACKS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("[4] - COKE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("[5] - ROYAL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("[6] - SPRITE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DRINKS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 152, 110, 30));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 30));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 30));
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 30));
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 182, 110, 30));
        getContentPane().add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 110, 30));
        getContentPane().add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 110, 30));

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setText("SHOW");
        btn1.addActionListener(this::btn1ActionPerformed);
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 110, 40));

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setText("TOTAL");
        btn2.addActionListener(this::btn2ActionPerformed);
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 263, 110, 40));

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setText("CALCULATE");
        btn3.addActionListener(this::btn3ActionPerformed);
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 100, 40));

        btn4.setBackground(new java.awt.Color(0, 153, 153));
        btn4.setText("ORDER AGAIN");
        btn4.addActionListener(this::btn4ActionPerformed);
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 120, 40));

        btn5.setBackground(new java.awt.Color(255, 0, 0));
        btn5.setText("EXIT");
        btn5.addActionListener(this::btn5ActionPerformed);
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 110, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("MENU");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        try {
            int choice = Integer.parseInt(txt1.getText());
            double price = 0.0;
            String name = "";

            if (choice == 1) 
            {
                name = "cheese cake";
                price = 30.00;
            } else if (choice == 2) 
            {
                name = "vanilla cake";
                price = 40.00;
            } else if (choice == 3) 
            {
                name = "chocolate cake";
                price = 45.00;
            } else if (choice == 4)
            {
                name = "coke";
                price = 35.00;
            } else if (choice == 5) 
            {
                name = "sprite";
                price = 25.00;
            } else if (choice == 6)
            {
                name = "royal";
                price = 35.00;
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please Enter 1-6!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            txt2.setText(name);
            txt3.setText("" + price);
            
            
        } catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(rootPane, "Please Enter 1-6!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
         try {

            if (txt3.getText().isEmpty()) 
            {
                JOptionPane.showMessageDialog(rootPane, "PLEASE CLICK SHOW BUTTON FIRST!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int quantity = Integer.parseInt(txt4.getText());
            double price = Double.parseDouble(txt3.getText());

            double total = price * quantity;
            txt5.setText("" + total);
            txt6.setText("" + total);

        } catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(rootPane, "PLEASE ENTER INVALID QUANTITY", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
              
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        try {
                if (txt6.getText().isEmpty()) 
                {
                    JOptionPane.showMessageDialog(rootPane, "PLEASE CLICK TOTAL BUTTON FIRST", "ERROR", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                double total = Double.parseDouble(txt6.getText());
                double cash = Double.parseDouble(txt7.getText());

                if (cash < total) 
                {
                    JOptionPane.showMessageDialog(rootPane, "INSUFFICIENT CASH!", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txt7.setText("");
                    txt7.requestFocus();
                    return;
                }

                double change = cash - total;
                txt8.setText("" + change);

                JOptionPane.showMessageDialog(rootPane, "THANK YOU FOR ORDERING!", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "ENTER VALID CASH!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }                               
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");
        txt4.setText("");
        txt5.setText("");
        txt6.setText("");
        txt7.setText("");
        txt8.setText("");        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
         
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CAFETERIA_ORDER2().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    // End of variables declaration//GEN-END:variables

}