/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.act.a;
import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class jhamaica extends javax.swing.JFrame {
    int p1lives = 5;
    int p2lives = 5;

    /**
     * Creates new form jhamaica
     */
    public jhamaica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rock = new javax.swing.JLabel();
        paper = new javax.swing.JLabel();
        scissor = new javax.swing.JLabel();
        p1health = new javax.swing.JLabel();
        p2health = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        vs = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rock.setText("[1] - ROCK");
        getContentPane().add(rock, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 80, 10));

        paper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paper.setText("[2] - PAPER");
        getContentPane().add(paper, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, 20));

        scissor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scissor.setText("[3] -  SCISSOR");
        getContentPane().add(scissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 20));

        p1health.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p1health.setText("PLAYER 1 HEALTH: 5");
        getContentPane().add(p1health, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        p2health.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        p2health.setText("PLAYER 2  HEALTH: 5");
        getContentPane().add(p2health, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        txt1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 150, 160, 40));

        txt2.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 170, 40));

        vs.setBackground(new java.awt.Color(204, 204, 204));
        vs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vs.setText("VS");
        vs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsActionPerformed(evt);
            }
        });
        getContentPane().add(vs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, 50));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsActionPerformed
        // TODO add your handling code here:
         int p1 = Integer.parseInt(txt1.getText());
         int p2 = Integer.parseInt(txt2.getText());
    
        
        if ((p1 == 1 && p2 == 1) || (p1 == 2 && p2 == 2) || (p1 == 3 && p2 == 3))
        {
            JOptionPane.showMessageDialog(rootPane, "DRAW", "RPS",JOptionPane.INFORMATION_MESSAGE);    
        }
        
        else if ((p1 == 1 && p2 == 3) || (p1 == 2 && p2 == 1) || (p1 == 3 && p2 == 2))
        {
            
            p2lives -= 1;
            p1health.setText("PLAYER 1 HEALTH: "+p1lives);
            p2health.setText("PLAYER 2 HEALTH: "+p2lives);
            JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WINS", "RPS",JOptionPane.INFORMATION_MESSAGE);    
        }
        
        else if ((p1 == 1 && p2 == 2) || (p1 == 2 && p2 == 3) || (p1 == 3 && p2 == 1))
        {
            
            p1lives -= 1;
            p1health.setText("PLAYER 1 HEALTH:  "+p1lives);
            p2health.setText("PLAYER 2 HEALTH:  "+p2lives);
            JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WINS", "RPS",JOptionPane.INFORMATION_MESSAGE);    
        }
        
        else
        {
            JOptionPane.showMessageDialog(rootPane, "PLEASE ENTER 1, 2 ,3 ONLY", "ERROR",JOptionPane.ERROR_MESSAGE); 
        }
        if (p1lives == 0 || p2lives == 0)
          {
          if (p1lives == 0)
          {
          JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WINS THE MATCH!", "GAME OVER!", JOptionPane.INFORMATION_MESSAGE); 
          }
          else 
          {
          JOptionPane.showMessageDialog(rootPane, "PLAYER 1 WINS THE MATCH!", "GAME OVER!" ,JOptionPane.INFORMATION_MESSAGE); 
          }
          
            p1lives = 5;
            p2lives = 5;
            p1health.setText("PLAYER 1 HEALTH:  "+p1lives);
            p2health.setText("PLAYER 2 HEALTH:  "+p2lives);

            txt1.setText("");
            txt2.setText("");    
          }    
    }//GEN-LAST:event_vsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jhamaica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jhamaica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jhamaica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jhamaica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jhamaica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p1health;
    private javax.swing.JLabel p2health;
    private javax.swing.JLabel paper;
    private javax.swing.JLabel rock;
    private javax.swing.JLabel scissor;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JButton vs;
    // End of variables declaration//GEN-END:variables
}
