/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.act.a;
import javax.swing.JOptionPane;

/**
 *
 * @author Jan Mark
 */
public class manalo extends javax.swing.JFrame {
    
    int p1lives = 5;
    int p2lives = 5;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manalo.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public manalo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rock = new javax.swing.JLabel();
        paper = new javax.swing.JLabel();
        scissor = new javax.swing.JLabel();
        p1health = new javax.swing.JLabel();
        p2health = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rock.setText("[1] - ROCK");
        getContentPane().add(rock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 80, 10));

        paper.setText("[2] - PAPER");
        getContentPane().add(paper, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 20));

        scissor.setText("[3] -  SCISSOR");
        getContentPane().add(scissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        p1health.setText("PLAYER 1 HEALTH 5");
        getContentPane().add(p1health, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        p2health.setText("PLAYER 2  HEALTH 5");
        getContentPane().add(p2health, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 150, 110, 30));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 150, 110, 30));

        jButton1.setText("VS");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       int p1 = Integer.parseInt(txt1.getText());
       int p2 = Integer.parseInt(txt2.getText());

       if ((p1 == 1 && p2 == 1) || (p1 == 2 && p2 == 2) || (p1 == 3 && p2 == 3))
     {
        JOptionPane.showMessageDialog(rootPane, "DRAW", "RPS", JOptionPane.INFORMATION_MESSAGE);
    }

      else if ((p1 == 1 && p2 == 3) || (p1 == 2 && p2 == 1) || (p1 == 3 && p2 == 2))
     {
    // Player 2 loses
      if (p1lives > 0)
    {
        p1lives--;
    }

    p1health.setText("PLAYER 1 HEALTH: " + p1lives);
    p2health.setText("PLAYER 2 HEALTH: " + p2lives);

       if (p1lives == 0)
    {
       JOptionPane.showMessageDialog(rootPane,"PLAYER 1 WINS THE GAME!","GAME OVER",JOptionPane.INFORMATION_MESSAGE);
    }
      else
    {
        JOptionPane.showMessageDialog(rootPane,"PLAYER 1 WINS", "RPS",JOptionPane.INFORMATION_MESSAGE);
    }
}

       else if ((p1 == 1 && p2 == 2) || (p1 == 2 && p2 == 3) || (p1 == 3 && p2 == 1))
{
    // Player 1 loses
     if (p2lives > 0)
    {
        p2lives--;
    }

    p1health.setText("PLAYER 1 HEALTH: " + p1lives);
    p2health.setText("PLAYER 2 HEALTH: " + p2lives);

     if (p2lives == 0)
    {
        JOptionPane.showMessageDialog(rootPane,"PLAYER 2 WINS THE GAME!","GAME OVER",JOptionPane.INFORMATION_MESSAGE);
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "PLAYER 2 WINS","RPS",JOptionPane.INFORMATION_MESSAGE);
    }
}

     else
     {
        JOptionPane.showMessageDialog(rootPane,"PLEASE ENTER 1, 2, 3 ONLY","ERROR",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new manalo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel p1health;
    private javax.swing.JLabel p2health;
    private javax.swing.JLabel paper;
    private javax.swing.JLabel rock;
    private javax.swing.JLabel scissor;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
